# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true
command_timeout = 10

# Change the default prompt format
format = """\
$directory
$character"""

right_format = """$all"""

# Change the default prompt characters
[character]
success_symbol = "[ï¡](bold blue)"
error_symbol = "[ï¡](bold red)"

[memory_usage]
disabled = false
threshold = 75
symbol = 'ó°›'
format = '[$ram_pct $symbol]($style) '
style = 'bold dimmed red'

[directory]
truncation_length = 4
truncation_symbol = "â€¦/"
home_symbol = "ó°‹œ ~"
read_only_style = "197"
read_only = " ï€£ "
style = "blue"
format = "[$path ï“”]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "î‚  "
format = "[on $symbol$branch]($style) "
truncation_symbol = "â€¦/"
style = "bold blue"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold blue"
conflicted = "ğŸ³"
up_to_date = "ï† "
untracked = "ï”© "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = "ï£– "
modified = "ï„ "
staged = '[++\($count\)](green)'
deleted = "ï€” "

[python]
symbol = "îœ¼ "
python_binary = "python"

[nodejs]
format = "via [ó°™ $version](bold green) "

[rust]
format = "via [î¨ $version](bold #fab387) "

[package]
symbol = 'ó°– '
